CLASS zcl_bc_ccm_step_comm_arr DEFINITION
  PUBLIC FINAL
  CREATE PUBLIC.

  PUBLIC SECTION.
    INTERFACES zif_bc_ccm_setup_step.

  PRIVATE SECTION.
    TYPES providers TYPE STANDARD TABLE OF ZBC_I_CCMProviderCust WITH EMPTY KEY.

    "! Read all configured providers from the system
    "! @parameter result | Provider Configuration
    METHODS get_all_providers
      RETURNING VALUE(result) TYPE providers.

    "! Get the list of configured arrangements
    "! @parameter result | List of providers
    METHODS get_communication_arrangements
      RETURNING VALUE(result) TYPE zcl_bc_ccm_provider_func=>providers.

    "! Create a new Communication Arrangement for the provider
    "! @parameter log                  | Log object
    "! @parameter provider_id          | Provider ID
    "! @parameter communication_system | Communication System for the CA
    METHODS create_new_arrangement
      IMPORTING !log                 TYPE REF TO zif_bc_ccm_mini_log
                provider_id          TYPE sca_ds_object_provider_id
                communication_system TYPE string.

ENDCLASS.


CLASS zcl_bc_ccm_step_comm_arr IMPLEMENTATION.
  METHOD zif_bc_ccm_setup_step~check.
    result = VALUE #(
        status  = zif_bc_ccm_setup_step=>status-ok
        message = ''
        log     = zcl_bc_ccm_mini_log_factory=>create_log( zif_bc_ccm_mini_log=>sub_objects-step_execute ) ).

    FINAL(all_providers) = get_all_providers( ).
    FINAL(customized_scenarios) = get_communication_arrangements( ).

    IF all_providers IS INITIAL.
      result-status  = zif_bc_ccm_setup_step=>status-intial.
      result-message = TEXT-002.
    ENDIF.

    LOOP AT all_providers INTO FINAL(provider).
      IF line_exists( customized_scenarios[ provider_id = provider-ProviderId ] ).
        CONTINUE.
      ENDIF.

      MESSAGE e024(zbc_ccm) WITH provider-ProviderId INTO result-log->message.
      result-log->add_message( ).

      result-message = TEXT-003.
      result-status  = zif_bc_ccm_setup_step=>status-changes.
    ENDLOOP.
  ENDMETHOD.


  METHOD zif_bc_ccm_setup_step~execute.
    result-log = zcl_bc_ccm_mini_log_factory=>create_log( zif_bc_ccm_mini_log=>sub_objects-step_execute ).

    FINAL(all_provider) = get_all_providers( ).
    FINAL(customized_scenarios) = get_communication_arrangements( ).
    FINAL(default_scenarios) = NEW zcl_bc_ccm_provider_func( )->get_all_object_providers( ).

    LOOP AT all_provider INTO FINAL(provider).
      IF line_exists( customized_scenarios[ provider_id = provider-ProviderId ] ).
        CONTINUE.
      ENDIF.

      TRY.
          FINAL(reference_scenario) = default_scenarios[ provider_id = provider-ProviderId ].
        CATCH cx_sy_itab_line_not_found.
          CONTINUE.
      ENDTRY.

      create_new_arrangement( log                  = result-log
                              provider_id          = provider-ProviderId
                              communication_system = reference_scenario-system_id ).
    ENDLOOP.
  ENDMETHOD.


  METHOD zif_bc_ccm_setup_step~get_description.
    RETURN TEXT-001.
  ENDMETHOD.


  METHOD zif_bc_ccm_setup_step~get_navigation.
    RETURN VALUE #( object = `CommunicationArrangement`
                    action = `maintain` ).
  ENDMETHOD.


  METHOD zif_bc_ccm_setup_step~get_step_id.
    RETURN CONV #( zif_bc_ccm_setup_step=>step-comm_arrangement ).
  ENDMETHOD.


  METHOD get_all_providers.
    SELECT FROM ZBC_I_CCMProviderCust
      FIELDS *
      WHERE Active = @abap_true
      INTO TABLE @result
      PRIVILEGED ACCESS.
  ENDMETHOD.


  METHOD get_communication_arrangements.
    RETURN NEW zcl_bc_ccm_provider_func( )->get_all_object_providers(
        scenario       = zcl_bc_ccm_remote_objects=>onprem_comm_scenario
        provider_field = 'PROVIDER_ID' ).
  ENDMETHOD.


  METHOD create_new_arrangement.
    FINAL(arrangement_api) = cl_com_arrangement_factory=>create_instance( ).
    FINAL(new_name) = |{ zcl_bc_ccm_remote_objects=>onprem_comm_scenario }_{ provider_id }|.

    TRY.
        arrangement_api->create_ca(
          EXPORTING iv_cscn_id            = CONV #( zcl_bc_ccm_remote_objects=>onprem_comm_scenario )
                    iv_cs_id              = CONV #( communication_system )
                    iv_name               = CONV #( new_name )
                    iv_description        = 'Generated by CCM Setup'
          " TODO: variable is assigned but only used in commented-out code (ABAP cleaner)
          IMPORTING eo_com_arrangement_v2 = FINAL(new_arrangement) ).

      CATCH cx_com_arrangement.
        MESSAGE e025(zbc_ccm) WITH provider_id INTO log->message.
        log->add_message( ).
    ENDTRY.

*    TRY.
*        FINAL(all_properties) = new_arrangement->get_properties( ).
*        FINAL(provider_property) = all_properties[ name = 'PROVIDER_ID' ].
*        new_arrangement->add_property_value( iv_property_uuid  = provider_property-uuid
*                                             is_property_value = VALUE #( value = provider_id ) ).
*
*      CATCH cx_sy_itab_line_not_found cx_com_arrangement.
*        MESSAGE e026(zbc_ccm) WITH provider_id INTO log->message.
*        log->add_message( ).
*    ENDTRY.

    MESSAGE s028(zbc_ccm) WITH provider_id new_name INTO log->message.
    log->add_message( ).
  ENDMETHOD.
ENDCLASS.
