CLASS zcl_bc_ccm_business_role DEFINITION
  PUBLIC FINAL
  CREATE PUBLIC.

  PUBLIC SECTION.
    TYPES:
      BEGIN OF role_setting,
        role_name        TYPE if_iam_business_role=>ty_id,
        description      TYPE if_iam_business_role=>ty_description,
        business_catalog TYPE if_iam_business_role=>ty_bu_catalog_id,
        assign_role      TYPE abap_boolean,
        user_id          TYPE if_iam_business_role=>ty_user_id,
      END OF role_setting.
    TYPES role_settings TYPE STANDARD TABLE OF role_setting WITH EMPTY KEY.

    METHODS constructor
      IMPORTING setting TYPE role_setting.

    "! Create a new role without save, to validate errors in configuration
    "! @parameter result | X = Ok, '' = Error
    METHODS create_role
      RETURNING VALUE(result) TYPE abap_boolean.

    "! Call save to create business role (UPDATE TASK)
    "! @parameter result | X = Ok, '' = Error
    METHODS save
      RETURNING VALUE(result) TYPE abap_boolean.

    "! Extract Setting for mass enablement
    "! @parameter result | All role parameters
    METHODS get_setting
      RETURNING VALUE(result) TYPE role_setting.

  PRIVATE SECTION.
    DATA role_name        TYPE if_iam_business_role=>ty_id.
    DATA !description     TYPE if_iam_business_role=>ty_description.
    DATA business_catalog TYPE if_iam_business_role=>ty_bu_catalog_id.
    DATA assign_role      TYPE abap_boolean.
    DATA user_id          TYPE if_iam_business_role=>ty_user_id.

    DATA new_role         TYPE REF TO if_iam_business_role.
    DATA log              TYPE REF TO zif_bc_ccm_mini_log.

    "! Checks, if the message table has errors
    "! @parameter messages | BAPIRET2 messages
    "! @parameter result   | X = Error, '' = Ok
    METHODS has_error
      IMPORTING !messages     TYPE bapirettab
      RETURNING VALUE(result) TYPE abap_boolean.

ENDCLASS.


CLASS zcl_bc_ccm_business_role IMPLEMENTATION.
  METHOD constructor.
    role_name        = setting-role_name.
    description      = setting-description.
    business_catalog = setting-business_catalog.
    assign_role      = setting-assign_role.

    TRY.
        IF setting-user_id IS NOT INITIAL.
          user_id = setting-user_id.
        ELSE.
          user_id = |CB{ cl_abap_context_info=>get_user_business_partner_id( ) }|.
        ENDIF.

      CATCH cx_abap_context_info_error.
        CLEAR assign_role.
    ENDTRY.
  ENDMETHOD.


  METHOD get_setting.
    RETURN VALUE #( role_name        = role_name
                    description      = description
                    business_catalog = business_catalog
                    assign_role      = assign_role
                    user_id          = user_id ).
  ENDMETHOD.


  METHOD create_role.
    FINAL(iam_role) = cl_iam_business_role_factory=>create_instance( ).

    iam_role->get_business_roles_by_id( EXPORTING it_id            = VALUE #( ( role_name ) )
                                        IMPORTING et_business_role = DATA(found_roles) ).
    IF lines( found_roles ) = 1.
      result = abap_true.
      RETURN.
    ENDIF.

    iam_role->create_business_role( EXPORTING iv_id            = role_name
                                    IMPORTING eo_business_role = new_role
                                              et_return        = DATA(messages) ).

    IF has_error( messages ).
      RETURN.
    ENDIF.

    new_role->set_description( EXPORTING iv_description = description
                               IMPORTING et_return      = messages ).
    IF has_error( messages ).
      RETURN.
    ENDIF.

    new_role->set_long_text( EXPORTING iv_text   = 'Generated by CCM Setup'
                             IMPORTING et_return = messages ).
    IF has_error( messages ).
      RETURN.
    ENDIF.

    new_role->add_business_catalog( EXPORTING iv_bu_catalog_id = business_catalog
                                    IMPORTING et_return        = messages ).
    IF has_error( messages ).
      RETURN.
    ENDIF.

    new_role->set_access_restriction( EXPORTING iv_write  = new_role->co_access_restriction_code-unrestricted
                                                iv_read   = new_role->co_access_restriction_code-unrestricted
                                                iv_f4     = new_role->co_access_restriction_code-unrestricted
                                      IMPORTING et_return = messages ).
    IF has_error( messages ).
      RETURN.
    ENDIF.

    new_role->add_flp_space( EXPORTING iv_flp_space_id = 'ZBC_CCM_SPACE'
                             IMPORTING et_return       = messages ).
    IF has_error( messages ).
      RETURN.
    ENDIF.

    IF assign_role = abap_true.
      new_role->add_user( EXPORTING iv_user_id = user_id
                          IMPORTING et_return  = messages ).
      IF has_error( messages ).
        RETURN.
      ENDIF.
    ENDIF.

    result = abap_true.
  ENDMETHOD.


  METHOD save.
    IF new_role IS NOT BOUND.
      RETURN abap_true.
    ENDIF.

    new_role->save( IMPORTING et_return = DATA(messages) ).

    IF has_error( messages ).
      RETURN abap_false.
    ELSE.
      RETURN abap_true.
    ENDIF.
  ENDMETHOD.


  METHOD has_error.
    LOOP AT messages INTO FINAL(message) WHERE type = 'E' OR type = 'A' OR type = 'X'.
      MESSAGE
        ID message-id
        TYPE message-type
        NUMBER message-number
        WITH message-message_v1 message-message_v2 message-message_v3 message-message_v4
        " TODO: variable is assigned but never used; add pragma ##NEEDED (ABAP cleaner)
        INTO FINAL(dummy_output).
    ENDLOOP.

    RETURN xsdbool( sy-subrc = 0 ).
  ENDMETHOD.
ENDCLASS.
